server:
  port: 9005
eureka:
    instance:
      hostname: localhost
    client:
      serviceUrl:
        #defaultZone: http://localhost:7001/eureka
        defaultZone: http://localhost:9005/eureka
      fetch-registry: false #是否到服务上抓取数据
      register-with-eureka: false #是否注册到注册中心
